name: cm-job
description: "A composite action that runs a Quarto command."

runs:
  using: "composite"
  steps:
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: '1.3.450'
