name: cm-job

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.3.450'