name: test reuse

on:
  push:

jobs:
  setup-quarto:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: run custom action
        uses: ./.github/actions/cm-job
        with:
          myInput: "someValue"
