name: test reuse

on:
  push:

jobs:
  setup-quarto:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: run custom action
        uses: ./.github/actions/cm-job.yml
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
          path: test.qmd