name: test reuse

on:
  push:

jobs:
  cm-job: 
    uses: ./.github/workflows/cm-job.yml
  setup-quarto:
    runs-on: ubuntu-22.04
    needs: [cm-job] 

    steps:
      - uses: actions/checkout@v3
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
          path: test.qmd