name: test reuse

on:
  push:

jobs:
  setup-quarto-r:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.3.450'
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
          path: source-folder # By default, the current working dir is used i.e `quarto render .`